name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Descompactar projeto Android
        run: |
          unzip -o IPTVPlayer-Android-Project.zip -d project
          find project -maxdepth 3 -type f | head -50

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.9'

      - name: Encontrar projeto Gradle
        run: |
          find project -name settings.gradle -o -name settings.gradle.kts

         - name: Localizar projeto Android
        run: |
          echo "Procurando settings.gradle..."
          find project -type f \( -name "settings.gradle" -o -name "settings.gradle.kts" \)

      - name: Gerar APK
        run: |
          PROJECT_DIR=$(dirname "$(find project -type f \( -name 'settings.gradle' -o -name 'settings.gradle.kts' \) | head -1)")
          echo "Projeto encontrado em: $PROJECT_DIR"
          cd "$PROJECT_DIR"
          gradle assembleDebug

      - name: Procurar APK
        run: |
          find project -type f -name "*.apk"

      - name: Salvar APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: project/**/build/outputs/apk/debug/*.apk